version: "3"

services:
  backend:
    container_name: backend
    image: noobtuber100/flexmoney:backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    container_name: frontend
    image: noobtuber100/flexmoney:frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
